# -*- coding: utf-8 -*-
"""tictactoe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Fx6EFQnaathMnOsflHOnMhfywRyuOx9
"""

# Tic-Tac-Toe

# Function to print the Tic-Tac-Toe board
def print_board(board):
    print("-------------")
    for i in range(3):
        print("|", end=" ")
        for j in range(3):
            print(board[i][j], "|", end=" ")
        print("\n-------------")

# Function to check if any player has won
def check_win(board, player):
    # Check rows
    for i in range(3):
        if board[i][0] == board[i][1] == board[i][2] == player:
            return True

    # Check columns
    for i in range(3):
        if board[0][i] == board[1][i] == board[2][i] == player:
            return True

    # Check diagonals
    if board[0][0] == board[1][1] == board[2][2] == player or board[0][2] == board[1][1] == board[2][0] == player:
        return True

    return False

# Function to play the game
def play_game():
    board = [[" " for _ in range(3)] for _ in range(3)]
    current_player = "X"
    print("Let's play Tic-Tac-Toe!")
    print_board(board)

    while True:
        # Get the player's move
        row = int(input("Enter the row (0, 1, 2): "))
        col = int(input("Enter the column (0, 1, 2): "))

        # Check if the move is valid
        if board[row][col] != " ":
            print("Invalid move! Try again.")
            continue

        # Make the move
        board[row][col] = current_player

        # Print the updated board
        print_board(board)

        # Check if the current player wins
        if check_win(board, current_player):
            print("Player", current_player, "wins!")
            break

        # Check if it's a tie
        if all(board[i][j] != " " for i in range(3) for j in range(3)):
            print("It's a tie!")
            break

        # Switch to the other player
        current_player = "O" if current_player == "X" else "X"

# Start the game
play_game()